name: Auto Wake LeanCloud

on: 
  push:
    tags:
    - 'v*'
  schedule:
    - cron: "*/15 0-15 * * ?"
  workflow_dispatch: 


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python           #安装python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install requests        #安装requests
      run: |
        pip install requests
    - name: Waking                  #读取站点信息
      env: 
        $CONFIG_SITE: ${{ secrets.Site }} # 读取评论后台地址
      run: | 
        python Get_SiteUrl.py ${{ secrets.Site }}
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
